/home/alta/relevance/vr311/attention-topic-model/preprocessing/get_bert_dists.py
/home/alta/relevance/vr311/attention-topic-model/preprocessing/get_bert_dists.py
/home/alta/relevance/vr311/attention-topic-model/preprocessing/get_bert_dists.py
/home/alta/relevance/vr311/attention-topic-model/preprocessing/get_bert_dists.py
/home/alta/relevance/vr311/attention-topic-model/preprocessing/make_bert_weights.py
/home/alta/relevance/vr311/attention-topic-model/preprocessing/make_bert_weights.py
/home/alta/relevance/vr311/attention-topic-model/preprocessing/make_bert_weights.py
/home/alta/relevance/vr311/attention-topic-model/preprocessing/make_bert_weights.py
./make_arr_unigrams.py
./make_arr_unigrams.py
./make_arr_unigrams.py
./make_arr_unigrams.py
./make_arr_unigrams.py
make_sbert_weights.py
make_sbert_weights.py
make_sbert_dists.py
make_sbert_dists.py
make_sbert_weights.py
./make_sorted_prompt-response.py
./make_prompt-resp_ids.py
./make_prompt-resp_ids.py
./make_prompt-resp_ids.py
./make_prompt-resp_ids.py
./make_prompt-resp_ids.py
./make_prompt-resp_ids.py
./make_prompt-resp_ids.py
./make_prompt-resp_ids.py
./make_sorted_responses.py
./make_sorted_responses.py
./make_sorted_responses.py
